config/routes.rb
Rails.application.routes.draw do
  get '/users/edit' => 'users#edit'
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  put '/profile/update' => 'users#profile_update'

  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }

  ActiveAdmin.routes(self)
  root 'static#home'
  get '/survey' => 'static#survey'

  # redirect all 'apply' pages (old name) to matching 'launch' pages
  get '/apply/:page', to: redirect('/launch/%{page}')

  # redirect from original home of 'checklist' page to new 'profile' page
  get '/checklist', to: redirect('/profile')

  patch '/checklist' => 'checklists#update'
  put '/checklist' => 'checklists#update_item'

  get '/resources', to: redirect('/resources/search')
  get '/resources/search' => 'resources#new'
  post '/resources/search' => 'resources#search'
  get '/resources/search/:id' => 'resources#results'
  get '/resources/:id' => 'resources#show'

  get '/reports/user_count'

  # must come before CMS - covers a CMS route, redirecting to Resource Matching
  get '/grow/obtain-funding', to: redirect('/resources/search')

  comfy_route :cms_admin, path: '/cms'
  comfy_route :cms, path: '/', sitemap: false # Make sure this routeset is defined last
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :accomplishments, dependent: :destroy
  has_many :checklist_items, through: :accomplishments
  has_many :custom_checklist_items, class_name: 'ChecklistItem', foreign_key: :created_by_user_id
  has_one :notebook

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end

  def get_notebook
    self.notebook || self.create_notebook!
  end

  def completed_checklist_items
    ChecklistItem.joins(:accomplishments)
      .where(accomplishments: { completed: true, user_id: id})
  end

  def disabled_checklist_items
    ChecklistItem.joins(:accomplishments)
      .where(accomplishments: { disabled: true, user_id: id})
  end

  def all_checklist_items
    ChecklistItem.where('created_by_user_id IS NULL or created_by_user_id = ?', id)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(resource)
    signed_in_root_path(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # GET /users/edit
  def edit
    @user = current_user
  end

  # GET /profile
  def profile
    @user = current_user
    @notebook_items = @user.get_notebook.attributes
      .reject!{ |attrib| ["id","user_id","created_at","updated_at"].include? attrib }
      .map{|item| {slug: item[0], name: NOTEBOOK_LABELS[item[0].to_sym], value: item[1]} }
    render 'profile'
  end

  # PUT /profile
  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params.reject { |_k, v| v.blank? })
      flash[:notice] = 'Account updated.'
      redirect_to action: :profile
    else
      flash[:alert] = 'Account not updated. Please try again.'
      redirect_to action: :edit
    end
  end

  # PUT /profile_update
  def profile_update
    @user = current_user
    @user.get_notebook.update(notebook_params)
    render(json: { notebook: notebook_params })
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def notebook_params
    params.require(:notebook).permit!
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.haml
- content_for(:body_class, 'profile')
.step
  .step-header.margin-bottom-0
    .step-title.text-center
      %i.icon.icon-large.icon-profile.white
      %h1 My Profile
      %h2 track progress and essential info

  .content-container{ style: 'width: 100%;' }
    = form_for(@user, as: :user, url: profile_path, method: 'PUT') do |u|
      = u.label :email
      = u.email_field :email
      = u.label :password
      = u.password_field :password, placeholder: 'Must be at least 6 characters long'
      = u.label :password_confirmation
      = u.password_field :password_confirmation, label: 'New password confirmation', placeholder: 'Please type new password again'
      = u.submit 'Save Account Changes', class: 'button primary expanded'
    %a.button.secondary.expanded{ href: profile_path } Back to Profile

app/views/users/profile.haml
- content_for(:body_class, 'profile')

.step
  .step-header.margin-bottom-0
    .step-title.text-center
      %i.icon.icon-large.icon-profile.white
      %h1 My Profile
      %h2 track progress and essential info

  .content-container{ style: 'width: 100%;' }
    %ul.accordion.modules.details{ "data-accordion" => "true", "data-allow-all-closed" => "true" }
      %li.accordion-item.is-active.modular-box{ "data-accordion-item" => "true" }
        %a.accordion-title.step-group-title.text-centered
          .step-group-title-text
            .text
              %strong My Settings
            .arrow
        .accordion-content{ "data-tab-content" => "true" }
          .row
            %strong Username:
            %div= @user.email
          %a.inline-block.margin-top-10{ href: users_edit_path, style: 'text-decoration: underline;' } Change Username or Password
          .margin-top-10
            If you have multiple businesses to keep track of, please
            = link_to('create an account for each of them', destroy_user_session_path(create_new_account: 'true'), { style: "text-decoration: underline;", method: :delete })
    %ul.accordion.modules.notebook{ "data-accordion" => "true", "data-allow-all-closed" => "true" }
      %li.accordion-item.is-active.modular-box{ "data-accordion-item" => "true" }
        %a.accordion-title.step-group-title.text-centered
          .step-group-title-text
            .text
              %strong My Notebook
            .arrow
        .accordion-content{ "data-tab-content" => "true" }
          = react_component('Notebook', { items: @notebook_items }, { class: 'notebook' })
    %ul.accordion.modules.checklist{ "data-accordion" => "true", "data-allow-all-closed" => "true" }
      %li.accordion-item.modular-box{ "data-accordion-item" => "true" }
        %a.accordion-title.step-group-title.text-centered
          .step-group-title-text
            .text
              %strong My Checklist
            .arrow
        .accordion-content{ "data-tab-content" => "true" }
          .intro-copy
            This is a list of most of the tasks necessary to plan, launch, and grow your business.
            .row
              %span.bullet.bullet-pencil &#x270e;
              .intro-copy-item Add and edit your own checklist items
            .row
              %span.bullet.bullet-minus &#8854;
              .intro-copy-item Cross out tasks that don't apply to you
            .row
              %span.bullet.bullet-plus &#8853;
              .intro-copy-item Reveal items you deleted
            .row
              %span.bullet.arrow-right
              .intro-copy-item Learn more about each section
          = render 'shared/user_checklist'
    %ul.accordion.modules{ "data-accordion" => "true", "data-allow-all-closed" => "true" }
      %li.accordion-item.modular-box{ "data-accordion-item" => "true" }
        %a.accordion-title.step-group-title.text-centered
          .step-group-title-text
            .text
              %strong My Funding Opportunities
            .arrow
        .accordion-content{ "data-tab-content" => "true" }
          Soon you will be able to save your funding opportunities here. In the meantime, explore them with our search tool.
          %a{ href: '/resources/search' }
            .step-card.media-object
              .media-object-section.middle
                %i.icon.icon-checklist
              .media-object-section.middle
                %strong Obtain Funding
                %div Resource matching
    %ul.accordion.modules.forms{ "data-accordion" => "true", "data-allow-all-closed" => "true" }
      %li.accordion-item.modular-box{ "data-accordion-item" => "true" }
        %a.accordion-title.step-group-title.text-centered
          .step-group-title-text
            .text
              %strong My Forms
            .arrow
        .accordion-content{ "data-tab-content" => "true" }
          Soon you will be able to save forms relevant to your business. Check back again soon!