config/routes.rb
Rails.application.routes.draw do
  get '/users/edit' => 'users#edit'
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  put '/profile/update' => 'users#profile_update'

  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }

  ActiveAdmin.routes(self)
  root 'static#home'
  get '/survey' => 'static#survey'

  # redirect all 'apply' pages (old name) to matching 'launch' pages
  get '/apply/:page', to: redirect('/launch/%{page}')

  # redirect from original home of 'checklist' page to new 'profile' page
  get '/checklist', to: redirect('/profile')

  patch '/checklist' => 'checklists#update'
  put '/checklist' => 'checklists#update_item'

  get '/resources', to: redirect('/resources/search')
  get '/resources/search' => 'resources#new'
  post '/resources/search' => 'resources#search'
  get '/resources/search/:id' => 'resources#results'
  get '/resources/:id' => 'resources#show'

  get '/reports/user_count'

  # must come before CMS - covers a CMS route, redirecting to Resource Matching
  get '/grow/obtain-funding', to: redirect('/resources/search')

  comfy_route :cms_admin, path: '/cms'
  comfy_route :cms, path: '/', sitemap: false # Make sure this routeset is defined last
end

app/views/shared/_analytics_report.haml
-# only used as a partial to include on the /analytics page,
-# which is otherwise managed in the CMS
-# this partial makes it easier to use chartkick stuff

= javascript_include_tag "https://www.google.com/jsapi", "chartkick"

-# Cumulative Users Over Time
- sum = 0 # helper for chart on next line - can maybe be refactored out
= line_chart User.where(role: nil).group_by_day(:created_at).order("day asc").count.map{ |x,y| { x => (sum += y)} }.reduce({}, :merge)

app/views/shared/_checklist.haml
- category ||= param_1
- embedded_in_form ||= false

- if embedded_in_form || user_signed_in?
  = render 'shared/checklist_items', category: category
- else
  = form_tag(checklist_path, method: 'patch') do
    = render 'shared/checklist_items', category: category
    = submit_tag "Save My Progress", { class: 'button primary expanded' }

app/views/shared/_checklist_item.haml
-# item_text | String
-# item_id | Integer
-# done | Boolean
-# disabled | Boolean

- if user_signed_in?
  = react_component('ChecklistItem', {id: item_id, text: item_text, completed: done, disabled: disabled }, {prerender: true, tag: 'ul'})
- else
  %li.checklist-item
    %input{ type: 'checkbox', id: "checklist-#{item_id}", name: 'checklist_items[]', value: item_id, checked: done }
    %label{ for: "checklist-#{item_id}" }
      = item_text

app/views/shared/_checklist_items.haml
- category

- if user_signed_in?
  - items = current_user.all_checklist_items.where(category: category).order(:order_number).map{ |item| item.with_state_for_user(current_user) }
  = react_component('Checklist', {items: items, category: category}, {prerender: true})
- else
  %input{ type: 'hidden', name: 'categories[]', value: category }
  - items = ChecklistItem.where(category: category).order(:order_number)
  = react_component('Checklist', {items: items, category: category, static_form: true}, {prerender: true})

app/views/shared/_contact_box.haml
- type = type || param_1 # ['phone', 'email']
- contact_info = contact_info || param_2

- if type == 'phone'
  %a.media-object.contact-box{ href:"tel:+1#{contact_info.gsub(/\D/, '')}"}
    .media-object-section.middle
      %div{ class:"contact-box_icon-#{type}" }
    .media-object-section.middle
      #{contact_info}
- elsif type == 'email'
  %a.media-object.contact-box{ href:"mailto:#{contact_info}" }
    .media-object-section.middle
      %div{ class:"contact-box_icon-#{type}" }
    .media-object-section.middle
      #{contact_info}

app/views/shared/_contact_box_combo.html.haml
- phone = phone || param_1
- email = email || param_2

.media-object.combo
  %a.contact-box{ href:"tel:+1#{phone.gsub(/\D/, '')}"} 
    .media-object-section.middle
      %div{ class:"contact-box_icon-phone" }
    .media-object-section.middle
      #{phone}
  %a.contact-box{ href:"mailto:#{email}" }
    .media-object-section.middle
      %div{ class:"contact-box_icon-email" }
    .media-object-section.middle
      #{email}

app/views/shared/_footer.html.haml
%footer.footer
  .row
    .columns.small-12.medium-6
      %div.margin-top-20
        %div.row 
          Designed and Built by
          %a{ href: 'https://www.codeforamerica.org/why-government/our-partners/long-beach-ca/'} Code for America
          and 
          %a{ href: 'http://longbeach.gov/iteam/'} Long Beach i-team
        %div.row
          Icons by 
          %a{ href: 'https://thenounproject.com/' } TheNounProject.com
        %div.row
          Open Source code on 
          %a{ href: 'https://github.com/codeforamerica/bizport' } Github
    .columns.small-12.medium-6

app/views/shared/_glossary.haml
-# make terms available for glossary.js
- terms_hash = GlossaryItem.pluck(:term, :definition).map{|item| { term: item[0], definition: item[1] } }.to_json
:javascript
  window.glossaryTerms = #{ terms_hash }

-# glossary.js really wants this item to exist - leaving it empty so it's 'invisible'
%button.js-glossary-toggle
#glossary.drawer{ "aria-describedby" => "glossary-result", "aria-hidden" => "true" }
  .close-bar
    .button--close{ title: "Close glossary" }
      .close-x.js-glossary-close= "\u00d7" # hex value for cross-mark character
  %h2.drawer-header Glossary
  %label.label{ for: "drawer-search" } Filter glossary terms
  %input.js-glossary-search.drawer-search{ placeholder: "e.g. business license", type: "search" }
  #glossary-result
    %ul.js-glossary-list{ accordion: "" }

app/views/shared/_google_translate.haml
#google_translate_element
  :javascript
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'en,es,hy,ja,km,ko,ru,tl,vi,zh-TW', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, gaTrack: true, gaId: 'UA-74906812-2'}, 'google_translate_element');
    }
  %script{:src => "//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit", :type => "text/javascript"}

app/views/shared/_header_nav_biz_steps.haml
%li
  %a{ href: start_business_plan_path } 1 Create a Business Plan
%li
  %a{ href: start_finance_your_business_path } 2 Finance Your Business
%li
  %a{ href: start_find_a_location_path } 3 Find a Location
%li
  %a{ href: start_choose_a_name_path } 4 Choose a Name
%li
  %a{ href: start_register_your_business_path } 5 Register Your Business
%li
  %a{ href: start_permits_and_licenses_path } 6 Permits and Licenses
%li
  %a{ href: start_building_and_inspections_path } 7 Building and Inspections
%li
  %a{ href: start_open_your_business_path } 8 Open Your Business

app/views/shared/_link_box.haml
- link = link || param_1
- line_1 = line_1 || param_2
- line_2 = line_2 || param_3

%a.media-object.link-box{ href: "#{link}", target: '_blank', onclick: "trackOutboundLink('#{link}')" }
  .media-object-section.middle
    .link-box_icon
  .media-object-section.middle
    %div #{line_1}
    %div #{line_2}

app/views/shared/_location_map.haml
- title = title || param_1
- address = address || param_2

- parsed_address = address.gsub(' ', '+')

%a.media-object.map-box{ href: "https://www.google.com/maps/place/#{parsed_address}/" }
  .map-box_title
    %div= title
    %div= address
  .map-box_image{ style: "background-image:url(http://maps.googleapis.com/maps/api/staticmap?center=#{parsed_address}&zoom=13&scale=false&size=400x200&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid|color:blue|#{parsed_address})", alt: "Google Map of #{address}" }

app/views/shared/_modular_box.haml
- type = type || param_1 # ['phone', 'email']
- content = content || param_2

- if type == 'phone'
  %a.contact-pane{ href: "tel:+1#{content.gsub(/\D/, '')}"}
    .contact-pane-section
      %i.icon{ class: "contact-box_icon-phone" }
    .contact-pane-section
      #{content}

- elsif type == 'email'
  %a.contact-pane{ href: "mailto:#{content}"}
    .contact-pane-section
      %i.icon{ class: "contact-box_icon-email" }
    .contact-pane-section
      #{content}

- elsif type == 'map'
  - address = content
  - parsed_address = content.gsub(' ', '+')

  %a.contact-pane{ href: "https://www.google.com/maps/place/#{parsed_address}/" }
    .map-box_image{ style: "background-image:url(http://maps.googleapis.com/maps/api/staticmap?center=#{parsed_address}&zoom=13&scale=false&size=400x200&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid|color:blue|#{parsed_address})", alt: "Google Map of #{address}" }
    .contact-pane-section
      %i.icon.icon-map
    .contact-pane-section
      = address

- else
  .contact-pane
    .contact-pane-section
      %i.icon{ class: "icon-#{type}" }
    .contact-pane-section
      #{content}

app/views/shared/_video_embed_youtube.haml
- youtube_embed_url = youtube_embed_url || param_1

.video-container
  %iframe{ frameborder: '0', id: 'ytplayer', src: youtube_embed_url, allowfullscreen: true, type: 'text/html' }