config/routes.rb
Rails.application.routes.draw do
  get '/users/edit' => 'users#edit'
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  put '/profile/update' => 'users#profile_update'

  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }

  ActiveAdmin.routes(self)
  root 'static#home'
  get '/survey' => 'static#survey'

  # redirect all 'apply' pages (old name) to matching 'launch' pages
  get '/apply/:page', to: redirect('/launch/%{page}')

  # redirect from original home of 'checklist' page to new 'profile' page
  get '/checklist', to: redirect('/profile')

  patch '/checklist' => 'checklists#update'
  put '/checklist' => 'checklists#update_item'

  get '/resources', to: redirect('/resources/search')
  get '/resources/search' => 'resources#new'
  post '/resources/search' => 'resources#search'
  get '/resources/search/:id' => 'resources#results'
  get '/resources/:id' => 'resources#show'

  get '/reports/user_count'

  # must come before CMS - covers a CMS route, redirecting to Resource Matching
  get '/grow/obtain-funding', to: redirect('/resources/search')

  comfy_route :cms_admin, path: '/cms'
  comfy_route :cms, path: '/', sitemap: false # Make sure this routeset is defined last
end

app/views/resources/new.haml
- content_for :title, "Opportunities"
- content_for :footer, "disable" # disables footer

.resources.new
  .step
    .step-header
      .step-title.text-center
        %i.icon.icon-large.icon-obtain-funding.white
        %h1 Obtain Funding
        %h2 Access resources to grow

    .content-container
      .row.columns.small-12.medium-8.medium-offset-2.large-6.large-offset-3
        = form_tag(resources_search_path, method: "post") do
          = hidden_field_tag(:city, 'Long Beach')
          = hidden_field_tag(:state, 'CA')
          = hidden_field_tag(:personal_investment, 1)
          = hidden_field_tag(:small_business, 1)

          -# Benefit Type
          %fieldset.row.benefit_types
            = label_tag(:benefit_types, "I need:", { class: 'fieldset-title' })
            - @benefit_types.select{ |bt| ['Money','Advice'].include? bt[:name] }.each do |benefit_type|
              .option-container.column.small-6
                .checkbox
                  %input{ type: 'checkbox', id: "benefit_type-#{benefit_type[:name].downcase}", name: 'benefit_types[]', checked: true, value: benefit_type[:id] }
                  %label{ for: "benefit_type-#{benefit_type[:name].downcase}" }
                .icon-container
                  .icon{ class: "icon-#{benefit_type[:name].downcase}" }
                  .benefit-name= benefit_type[:name]

          -# Purposes
          %fieldset
            = label_tag(:purposes, "I want support for:", { class: 'fieldset-title' })
            %label (check all that apply)
            - @purposes.each do |purpose|
              .option
                %input{ type: 'checkbox', id: "purpose-#{purpose[:name].downcase}", name: 'purposes[]', value: purpose[:id] }
                %label{ for: "purpose-#{purpose[:name].downcase}" }= purpose[:name]
            .option
              %input{ type: 'checkbox', id: "purpose-other", name: 'purposes[]', value: 'Other' }
              %label{ for: "purpose-other" } Other

          -# Existing Business
          %fieldset
            %label.fieldset-title I am:
            .option
              %input{ type: 'radio', id: "existing_business_new", name: 'existing_business', value: 'new' }
              %label{ for: 'existing_business_new' } Starting a new business
            .option
              %input{ type: 'radio', id: "existing_business_existing", name: 'existing_business', value: 0 }
              %label{ for: 'existing_business_existing' } Growing an existing business

          -# Industry
          %fieldset
            %label.fieldset-title My industry is:
            %label (check all that apply)
            - @industries.each do |industry|
              .option
                %input{ type: 'checkbox', id: "industry-#{industry[:name].downcase}", name: 'industries[]', value: industry[:id] }
                %label{ for: "industry-#{industry[:name].downcase}" }= industry[:name]

          %input.resources-fixed-cta.margin-top-10{:name => "commit", :type => "submit", :value => "Search Opportunities"}

app/views/resources/results.haml
- content_for :title, "Obtain Funding"
- content_for :footer, "disable" # disables footer

.resources.results
  .row.columns.small-12.medium-8.medium-offset-2.large-6.large-offset-3
    .header-text #{@search_data['results'].count} opportunities for me
    - @search_data['results'].each do |result|
      %a.result{ href: "/resources/#{result['id']}" }
        .value-prop
          - type = result['benefit_types'].try(:[], 0).try(:[], 'name')
          .icon{ class: "icon-#{type.downcase}" }
          .value-prop_text= result['value_prop']
        .descriptor.title
          %strong.text Opportunity:
          %span.text= result['title']
        - if result['purposes'].count > 0
          .descriptor.purpose
            %strong.text Purpose:
            %span.text= result['purposes'].map{ |p| p['name'] }.join(', ')
        - if result['industries'].count > 0
          .descriptor.industry
            %strong.text Industry:
            %span.text= result['industries'].map{ |i| i['name'] }.join(', ')

    %a.resources-fixed-cta{ href: resources_search_path }
      .resources-fixed-cta-text Search Again

app/views/resources/show.haml
- content_for :title, "Opportunities"
- content_for :footer, "disable" # disables footer

- agency = @opportunity['agency']

.resources.show
  .row.columns.small-12.medium-8.medium-offset-2.large-6.large-offset-3
    .value-prop
      - type = @opportunity['benefit_types'].try(:[], 0).try(:[], 'name')
      - if type == 'Money'
        .icon.icon-money
      - if type == 'Advice'
        .icon.icon-advice
      .value-prop_text= @opportunity['value_prop']
    .opp-details
      %table
        %tbody
          %tr
            %td Purpose:
            %td= @opportunity['title']
          - if @opportunity['purposes'].count > 0
            %tr
              %td Opportunity:
              %td= @opportunity['purposes'].map{ |p| p['name'] }.join(', ')
          %tr
            %td Source:
            %td= agency['name']
          %tr
            %td Contact:
            %td
              - if agency['phone'].present?
                %p
                  %a{ href: "tel: #{agency['phone']}" }= agency['phone']
              - if agency['fax'].present?
                %p
                  = agency['fax']
                  (fax)
              - if agency['street_address'].present?
                %p
                  = agency['street_address']
              - if agency['email'].present?
                %p
                  %a{ href: "mailto: #{agency['email']}" }= agency['email']
              - if agency['url'].present?
                %p
                  %a{ href: agency['url'] }= agency['url']
          %tr
            %td Application:
            %td
              %a{ href: @opportunity['application_link'], onclick: "trackOutboundLink('#{@opportunity['application_link']}')"}= @opportunity['application_link']
          - if @opportunity['industries'].count > 0
            %tr
              %td Industry:
              %td= @opportunity['industries'].map{ |p| p['name'] }.join(', ')
          - if @opportunity['small_business'] || @opportunity['personal_investment']
            %tr
              %td To Qualify:
              %td
                - if @opportunity['small_business']
                  %div.margin-bottom-10
                    You must be a small business. Check
                    %a{ href: 'https://www.sba.gov/contracting/getting-started-contractor/make-sure-you-meet-sba-size-standards/table-small-business-size-standards', onclick: "trackOutboundLink('https://www.sba.gov/contracting/getting-started-contractor/make-sure-you-meet-sba-size-standards/table-small-business-size-standards')" } this website to see if you are.
                - if @opportunity['personal_investment']
                  %div You need to invest some of your own money into your business.
          %tr
            %td Description:
            / Description in next `row` below
    .row.description
      = @opportunity['description']
    %a.resources-fixed-cta{ href: @opportunity['application_link'], onclick: "trackOutboundLink('#{@opportunity['application_link']}')"}
      .resources-fixed-cta-text APPLY