config/routes.rb
Rails.application.routes.draw do
  get '/users/edit' => 'users#edit'
  get '/profile' => 'users#profile'
  put '/profile' => 'users#update'
  put '/profile/update' => 'users#profile_update'

  devise_for :users, controllers: {
    passwords: 'users/passwords'
  }

  ActiveAdmin.routes(self)
  root 'static#home'
  get '/survey' => 'static#survey'

  # redirect all 'apply' pages (old name) to matching 'launch' pages
  get '/apply/:page', to: redirect('/launch/%{page}')

  # redirect from original home of 'checklist' page to new 'profile' page
  get '/checklist', to: redirect('/profile')

  patch '/checklist' => 'checklists#update'
  put '/checklist' => 'checklists#update_item'

  get '/resources', to: redirect('/resources/search')
  get '/resources/search' => 'resources#new'
  post '/resources/search' => 'resources#search'
  get '/resources/search/:id' => 'resources#results'
  get '/resources/:id' => 'resources#show'

  get '/reports/user_count'

  # must come before CMS - covers a CMS route, redirecting to Resource Matching
  get '/grow/obtain-funding', to: redirect('/resources/search')

  comfy_route :cms_admin, path: '/cms'
  comfy_route :cms, path: '/', sitemap: false # Make sure this routeset is defined last
end

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? "BizPort | "+yield(:title) : "BizPort"
    - if Rails.env.production?
      = render 'shared/analytics_ga' # must be inline for domain verification
      = javascript_include_tag 'analytics'
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'print', media: 'print'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body.no-js
    - if notice
      .notice.padding-all-10= notice
    - if alert
      .alert= alert
    .off-canvas-wrapper
      .off-canvas-wrapper-inner{"data-off-canvas-wrapper" => true}
        / off-canvas title bar and menu
        .title-bar
          .title-bar-left
            %span.title-bar-title
              %a{ href: root_path }
                %span BizPort
          .title-bar-right
            %button.menu-icon{"data-open" => "offCanvasRight", type: "button"} MENU
        / off-canvas right menu
        #offCanvasRight.off-canvas.position-right{"data-off-canvas" => true, "data-position" => "right"}
          .user-account-area
            - if user_signed_in?
              .log-button= link_to('Sign Out', destroy_user_session_path, method: :delete, class: '')
              %a.row{ href: dashboard_path }
                .icon.icon-profile.pull-right
                - split_email = current_user.email.split('@')
                .user-name
                  = split_email[0]
                  = '@'+split_email[1]
            - else
              .row
                .log-button= link_to 'Log In', new_user_session_path, class: 'pull-right'

          %ul.vertical.menu{"data-dropdown-menu" => true}
            %li
              #google_translate_element{style: 'margin-left: 15px; padding-top: 15px;'}
              :javascript
                function googleTranslateElementInit() {
                  new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'en,es,hy,km,ko,tl,vi,zh-TW', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, gaTrack: true, gaId: 'UA-74906812-2'}, 'google_translate_element');
                }
              %script{:src => "//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit", :type => "text/javascript"}
            %li
              %a{ href: root_path } Home
            %li
              %a{ href: survey_path } Survey
            %li
              %a{ href: checklist_path } My Checklist
            %li
              %a{ href: contact_path } Contact
            - ['plan','apply','grow'].each do |step_group|
              %li.title
                = step_group.titleize
              %ul
                = render 'shared/header_nav_biz_steps', step_groups: [step_group]
        / original content goes in this container
        .off-canvas-content{"data-off-canvas-content" => true}
          = yield
          - unless yield(:footer) == "disable"
            = render 'shared/footer'
    = render 'shared/glossary'

app/views/layouts/application.html.haml
!!!
%html{ lang: "en"}
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{ charset: "utf-8"}
    %meta{ content: "width=device-width, initial-scale=1.0", name: "viewport"}
    - # OPEN GRAPH
    - page_url = Comfy::Cms::Page.find_by_full_path(request.path).try(:url) || "bizport.longbeach.gov"
    %meta{:content => "http:#{page_url}", :property => "og:url"}/
    %meta{:content => "Long Beach Business Portal", :property => "og:title"}/
    %meta{:content => "Everything you need to plan, launch, and grow a business in Long Beach, California.", :property => "og:description"}/
    %meta{:content => ('http://bizport.longbeach.gov'+image_path('og_image.jpg')), :property => "og:image"}/
    %meta{:content => '1200', :property => "og:image:width"}/
    %meta{:content => '631', :property => "og:image:height"}/
    %meta{:content => "website", :property => "og:type"}/

    - # Twitter
    %meta{:content => "summary_large_image", :name => "twitter:card"}/
    %meta{:content => "@iteam_LongBeach", :name => "twitter:site"}/
    %meta{:content => "Long Beach Business Portal", :name => "twitter:title"}/
    %meta{:content => "Everything you need to plan, launch, and grow a business in Long Beach, California.", :name => "twitter:description"}/
    %meta{:content => ('http://bizport.longbeach.gov'+image_path('og_image.jpg')), :name => "twitter:image"}/

    %title= content_for?(:title) ? "Business Portal | "+yield(:title) : "Business Portal"
    - if Rails.env.production?
      = render 'shared/analytics_ga' # must be inline for domain verification
      = javascript_include_tag 'analytics'
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'print', media: 'print'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body.no-js{ class: [yield(:body_class), category_class].join(' ') }
    - if notice
      .notice.padding-all-10= notice
    - if alert
      .alert= alert
    .off-canvas-wrapper
      .off-canvas-wrapper-inner{"data-off-canvas-wrapper" => true}
        / off-canvas title bar and menu
        .title-bar
          .title-bar-left
            %span.title-bar-title
              %a{ href: root_path }
                %span Business Portal
          .title-bar-right
            %button.menu-icon{"data-open" => "offCanvasRight", type: "button"}
              .div Menu
        - if request.path == '/' && session[:dismiss_gt] != true # saves user pref to disable bar
          .translate-bar
            = render 'shared/google_translate'
            = link_to '&#9447;'.html_safe, { dismissgt: true }, class: 'dismiss-gt-link', 'aria-label' => 'Disable Google Translate bar'
        / off-canvas right menu
        #offCanvasRight.off-canvas.position-right{"data-off-canvas" => true, "data-position" => "right"}
          .user-account-area
            - if user_signed_in?
              .log-button= link_to('Sign Out', destroy_user_session_path, method: :delete)
              %a.row{ href: profile_path }
                .icon.icon-profile.pull-right
                - split_email = current_user.email.split('@')
                .user-name
                  = split_email[0]
                  = '@'+split_email[1]
            - else
              .row
                .log-button= link_to 'Log In', new_user_session_path, class: 'pull-right'

          %ul.vertical.menu{"data-dropdown-menu" => true}
            - unless request.path == '/'
              %li
                .google-translate-sidebar
                  = render 'shared/google_translate'
            %li
              %a{ href: root_path } Home
            %li
              %a{ href: survey_path } Survey
            %li
              %a{ href: profile_path } My Profile
            %li
              %a{ href: '/contact' } Contact
            - ['plan','launch','grow'].each do |step_group|
              %li.title
                = step_group.titleize
              %ul
                = render 'shared/header_nav_biz_steps', step_groups: [step_group]
        / original content goes in this container
        .off-canvas-content{"data-off-canvas-content" => true}
          = yield
          - unless yield(:footer) == "disable"
            = render 'shared/footer'
    = render 'shared/glossary'